---
name: Build

"on": [push]

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          # renovate datasource: github-runners, depName: ubuntu
          - ubuntu-22.04
          # renovate datasource: github-runners, depName: macos
          - macos-14

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: parse-tool-versions
        uses: paulo-ferraz-oliveira/parse-tool-versions@534819f70c0c04d788b49dafc29c8117901277bd # v1.0.3
        id: tool-versions

      - name: nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{steps.tool-versions.outputs.nodejs}}

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          command: markdownlint-cli2 _version
