---
name: Build

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  plugin_test:
    name: asdf plugin test

    strategy:
      matrix:
        os:
          # renovate datasource: github-runners, depName: ubuntu
          - ubuntu-22.04
          # renovate datasource: github-runners, depName: macos
          - macos-14

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: nodejs
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc

      - name: plugin-test
        uses: asdf-vm/actions/plugin-test@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          command: markdownlint-cli2 _version
